os: linux
dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - ./travis/before_install.sh

install:
  - ./travis/install.sh

script:
  - ./travis/script.sh

after_success:
  - ./travis/after_success.sh

after_failure:
  - ./travis/after_failure.sh

cache:
  - directories:
    - $HOME/.cache/pb
    - $HOME/.ccache

# We don't want to trigger travis builds for auto PR because there are
# too many of them and they are updated very frequently. travis can
# barely catchup and so causing the build status of these PRs always
# being shown as pending.